import type { KnowledgeDetail } from "./types";

export const modelKnowledge: Record<string, KnowledgeDetail> = {
  fft: {
    slug: "fft",
    title: "FFT",
    english: "Fast Fourier Transform",
    category: "信号处理 / 频域分析",
    layer: "模型层",
    difficulty: 2,
    summary: "把一段异响声音从时域拆成频率成分，看清异常能量集中在哪些频带。声学故障项目里绝大多数频域特征都建立在 FFT 之上",
    why: "异响在时域上很难看出问题，因为信号是转速和部件耦合的结果。FFT 把声音拆到频率轴上，才能跟转速、谐波、部件特征频带对齐。",
    engineeringProblem: "从一段控制件声音中识别主频、谐波和异常频带，把这些频域特征交给 Random Forest 或 CNN 判断故障类型",
    inputs: ["等间隔采样的声音或振动时域序列", "采样频率（决定可分析的最高频率）", "同步记录的转速、负载和工况"],
    outputs: ["频率—幅值谱或功率谱", "主频和峰值频率列表", "各阶谐波幅值", "可继续构造的频带能量、谐波比等特征"],
    principle: [
      "DFT 用离散方式计算有限长度序列的频率组成；FFT 是更高效地计算 DFT 的算法族",
      "频率分辨率等于采样窗口长度的倒数：窗口越长，分辨率越高，频谱越准",
      "工程上必须同时管采样率、窗口长度、加窗和频段对齐，否则谱峰会被误读",
    ],
    diagram: ["声音时域波形", "去直流 / 加窗", "FFT", "频率—幅值谱", "主频 / 谐波 / 频带能量", "Random Forest 或 CNN 分类"],
    exampleTitle: "最小示例｜定位异响主频",
    example: [
      "采集一段固定转速下的控制件声音，记录采样率",
      "按转速周期对信号分帧加窗，执行 FFT",
      "画出幅值谱，对比正常样本与异响样本在 1 kHz 附近的峰",
      "把峰频、谐波比、频带能量加入特征表交给分类模型",
    ],
    engineeringCase: "声学项目里 FFT 是基线：先确认主频是否随转速同步变化、谐波结构是否异常，再决定是否上 STFT 或 CNN。",
    suitable: ["稳定工况下的周期性异响分析", "构造频域特征喂给机器学习", "识别部件特征谐波"],
    unsuitable: ["强非平稳信号只看整段 FFT", "采样率不足或转速/负载未同步", "只凭一个谱峰直接下故障结论"],
    pitfalls: ["把采样率和频率分辨率混为一谈", "忽略加窗造成的谱泄漏", "不同转速样本直接比固定频率", "把环境噪声峰当成部件故障特征"],
    next: [
      { label: "STFT / 声谱图", href: "/business/acoustic" },
      { label: "Random Forest", href: "/models/random-forest" },
      { label: "声学故障专题", href: "/business/acoustic" },
    ],
    projects: [
      { label: "控制件声学故障：频域分析", href: "/business/acoustic" },
      { label: "AI 标定：NVH 评价扩展", href: "/business/calibration" },
    ],
  },
  "random-forest": {
    slug: "random-forest",
    title: "Random Forest",
    english: "Random Forest",
    category: "机器学习 / 集成学习",
    layer: "模型层",
    difficulty: 2,
    summary: "用多棵决策树投票做故障分类，给出特征重要性，对中小规模结构化数据非常稳。诊断和声学项目里的默认基线",
    why: "诊断特征表（频带能量、温升速率、扭矩波动等）通常样本量在几百到几万，特征有非线性，标签类别不平衡——Random Forest 几乎总能先跑出一个可信结果。",
    engineeringProblem: "根据温度、电流、转速统计量、频带能量等结构化特征，预测故障类型、严重等级或异常状态",
    inputs: ["按样本整理的特征矩阵 X（每行一段信号或一次试验）", "监督学习标签 y，例如故障类型", "训练 / 验证 / 测试划分（按车辆或试验批次）"],
    outputs: ["类别预测和概率", "特征重要性（按 Gini 减少量或置换重要度）", "可继续接 SHAP 输出单样本解释"],
    principle: [
      "Bootstrap 抽样：每棵树看到不同的样本子集",
      "特征随机性：每棵树分裂时只看随机一部分特征，降低树之间的相关性",
      "集成投票：分类任务多数表决，回归任务取平均；特征重要性来自特征被随机替换后模型性能下降程度",
    ],
    diagram: ["工程特征表", "Bootstrap 抽样", "多棵决策树", "投票 / 概率平均", "故障类别", "特征重要性 / SHAP"],
    exampleTitle: "最小示例｜用频域特征做异响分类",
    example: [
      "每段声音提取 RMS、峭度、主频、5 个频带能量",
      "按车辆或试验批次划分训练和测试集，避免同一次采集被拆两边",
      "训练 Random Forest，看混淆矩阵和召回率",
      "对误判样本回到原始声音和工况复核，不只调模型",
    ],
    engineeringCase: "诊断项目里 Random Forest 用来做故障分类；声学项目里接在 FFT/MFCC 之后做频谱特征分类。两者都是复杂深度网络前的强基线。",
    suitable: ["中小规模结构化数据", "需要看特征重要性", "需要先建可信基线", "特征与目标关系存在非线性"],
    unsuitable: ["直接吃非常长的原始波形", "需要精确外推连续物理规律", "类别极度不平衡且不做专门评估"],
    pitfalls: ["只看 Accuracy，不看召回率和混淆矩阵", "随机切分时把同一车辆相邻片段分到训练和测试", "把特征重要性误当因果关系", "类别不平衡时不专门处理"],
    next: [
      { label: "XGBoost", href: "/models/machine-learning" },
      { label: "SHAP 解释单样本预测", href: "/models/machine-learning" },
      { label: "机器学习 / 集成学习方向", href: "/models/machine-learning" },
      { label: "车辆诊断专题", href: "/business/diagnosis" },
    ],
    projects: [
      { label: "车辆诊断：故障分类", href: "/business/diagnosis" },
      { label: "声学故障：频谱特征分类", href: "/business/acoustic" },
    ],
  },
  "bayesian-optimization": {
    slug: "bayesian-optimization",
    title: "Bayesian Optimization",
    english: "Bayesian Optimization",
    category: "优化算法 / 黑盒优化",
    layer: "模型层",
    difficulty: 3,
    summary: "实车或台架试验昂贵，不能穷举参数。Bayesian Optimization 用代理模型找最值得试的下一组参数",
    why: "AI 标定的硬约束是试验成本。BO 适合评价函数不可导、单次评价昂贵、试验次数有限、需要显式利用历史结果的黑盒寻优。",
    engineeringProblem: "在标定参数上下界和安全约束内，用尽可能少的实车试验找到驾驶性更好的参数组合",
    inputs: ["待优化参数及上下界", "每组参数对应的评价分数", "可选：约束、噪声、多目标"],
    outputs: ["下一组建议试验参数", "当前最优参数", "代理模型对参数空间的预测与不确定性", "多目标场景下可扩展为 Pareto 候选"],
    principle: [
      "代理模型根据已完成试验拟合参数和评价的关系，同时估计不确定性",
      "采集函数在利用当前最优区域和探索不确定区域之间权衡",
      "每完成一次新试验就更新代理模型，再选下一点",
    ],
    diagram: ["历史标定试验", "代理模型（高斯过程 / TPE）", "采集函数", "候选参数", "实车 / 台架评价", "更新数据"],
    exampleTitle: "最小示例｜两个标定参数寻优",
    example: [
      "定义两个标定参数的上下界和综合评分函数",
      "先做 10-20 组初始试验得到样本",
      "训练代理模型，用采集函数选下一组参数",
      "实车或仿真跑后回填评分，循环到试验预算耗尽或评分收敛",
    ],
    engineeringCase: "内部 AI 标定方案的三模型链路是：驾驶性评价模型 → 参数优化模型 → 参数校验模型。BO 是参数优化模型的候选方法，必须配合安全校验和实车闭环。",
    suitable: ["单次试验昂贵", "参数维度中低、边界明确", "评价函数只能通过试验获得", "希望显式利用历史试验"],
    unsuitable: ["维度极高且单次评价便宜", "没有稳定的评价函数", "安全约束无法表达且不允许试错"],
    pitfalls: ["把代理模型预测当实车效果", "没有独立安全校验就直接下发参数", "把多目标压成单一分数且权重未经验证", "不同工况试验混在一起没有归一化"],
    next: [
      { label: "AI 标定专题", href: "/business/calibration" },
      { label: "多目标优化", href: "/models/machine-learning" },
      { label: "Agent 工作流", href: "/applications/agent" },
    ],
    projects: [
      { label: "AI 标定：参数寻优", href: "/business/calibration" },
      { label: "诊断模型超参数优化", href: "/business/diagnosis" },
      { label: "声学模型超参数优化", href: "/business/acoustic" },
    ],
  },
};

export const applicationKnowledge: Record<string, KnowledgeDetail> = {
  agent: {
    slug: "agent",
    title: "Agent",
    english: "AI Agent",
    category: "大模型应用 / 工作流编排",
    layer: "应用层",
    difficulty: 3,
    summary: "Agent 不负责精确计算，负责把 LLM、模型、工具、状态、审批串成可追踪的工程流程。诊断和标定里凡是多步任务，都靠它把环节接起来",
    why: "诊断不是一次问答，标定不是一次回归。一个真实闭环要读数、识工况、调模型、查规则、等试验、决定是否继续——Agent 就是为这种编排而生的。",
    engineeringProblem: "把已有模型、数据脚本、知识库、参数校验和人工审批组织成可追踪的多步工程流程",
    inputs: ["用户任务或工程事件", "当前状态 State", "可调用工具 Tools", "业务知识和安全规则"],
    outputs: ["结构化中间状态", "工具调用结果", "路由 / 继续 / 回退决策", "最终报告或下一步工程动作"],
    principle: [
      "LLM 负责理解任务和选工具，精确计算交给专用模型和工具",
      "State 跨步骤共享信息，避免每步从零开始",
      "Workflow 定义节点、路由、循环、终止和人工审批边界",
    ],
    diagram: ["任务输入", "LLM / Planner", "Tool 调用", "State 更新", "条件路由", "Human-in-the-loop"],
    exampleTitle: "最小示例｜驾驶性标定 Agent",
    example: [
      "ConditionAgent 读 CSV 输出工况",
      "DiagnosisAgent 读 CSV + 工况输出缺陷与评分",
      "CalibrationAgent 调参数策略或优化器出参数，过安全工具",
      "实车回采后 VerificationAgent 对比评分，决定收敛 / 继续 / 回退",
    ],
    engineeringCase: "内部驾驶性标定 Demo 用 LangChain + LangGraph 编排 4 个子 Agent，状态写入 CalibrationState。注意实车测试环节尚未接入，是工作流原型不是已闭环系统。",
    suitable: ["多个明确步骤和工具的工程任务", "需要保存中间状态并按结果路由", "需要接入 RAG、模型、数据库或业务 API", "需要人工审批和过程日志"],
    unsuitable: ["一个函数能完成的简单任务", "把 LLM 当精确计算器或底层控制器", "没有安全边界却让 Agent 自主下发高风险参数"],
    pitfalls: ["让 LLM 直接猜参数而不调优化器", "没有状态模型，靠长 Prompt 隐式保存流程", "把 Agent 数量当能力指标", "缺 Human-in-the-loop、日志和回退"],
    next: [
      { label: "RAG", href: "/applications/rag" },
      { label: "LangGraph", href: "/models/deep-learning" },
      { label: "AI 标定专题", href: "/business/calibration" },
    ],
    projects: [
      { label: "AI 标定 Agent", href: "/business/calibration" },
      { label: "诊断 Agent", href: "/business/diagnosis" },
    ],
  },
  rag: {
    slug: "rag",
    title: "RAG",
    english: "Retrieval-Augmented Generation",
    category: "大模型应用 / 企业知识",
    layer: "应用层",
    difficulty: 3,
    summary: "企业故障案例和技术规范不在通用大模型里。RAG 先检索相关材料，再让 LLM 基于这些材料生成可追溯的回答",
    why: "故障后分析和工程问答需要可追溯依据。RAG 的价值不是让模型知道更多，而是把回答锚定到企业文档和历史案例。",
    engineeringProblem: "让工程师能从大量故障案例、技术文档和维修手册中快速找到相关证据，并生成带来源的解释或排查建议",
    inputs: ["PDF / Word / Markdown 等企业文档", "文档切分后的 Chunk", "用户问题", "Embedding 与向量索引"],
    outputs: ["相关文档片段", "带来源的 LLM 回答", "可展示的引用列表", "可继续交给 Agent 的结构化知识"],
    principle: [
      "文档解析与切分，建立适合检索的 Chunk",
      "Chunk 编码成向量并建立向量索引",
      "提问时先检索相关 Chunk，再交给 LLM 生成答案并保留来源",
    ],
    diagram: ["企业文档", "解析 / Chunk", "Embedding", "Vector DB", "Retrieval", "LLM", "带依据回答"],
    exampleTitle: "最小示例｜历史异响案例问答",
    example: [
      "把维修手册和历史异响案例切分建索引",
      "输入某转速区间出现异响并伴随扭矩波动有哪些相似案例",
      "检索相似案例并按车型、工况过滤",
      "LLM 仅基于检索结果组织候选原因、证据和建议检查项",
    ],
    engineeringCase: "RAG 适合故障后知识复用、标定经验检索和技术规范问答。它不替代 CAN/声音的数值模型，而是补充文档知识。",
    suitable: ["企业内部知识问答", "历史案例检索", "技术规范和维修手册辅助", "需要答案可追溯来源"],
    unsuitable: ["精确时序预测", "控制策略实时计算", "没有文档质量治理却期待高可靠答案"],
    pitfalls: ["切分过粗或过细导致上下文丢失", "只做向量检索不用元数据过滤", "检索不到仍让模型强行回答", "没有展示来源无法工程复核"],
    next: [
      { label: "Agent", href: "/applications/agent" },
      { label: "文档数据", href: "/data" },
      { label: "车辆诊断专题", href: "/business/diagnosis" },
    ],
    projects: [
      { label: "诊断：相似案例检索", href: "/business/diagnosis" },
      { label: "标定：历史标定经验检索", href: "/business/calibration" },
    ],
  },
};
