import type { KnowledgeDetail } from "./types";

export const modelKnowledge: Record<string, KnowledgeDetail> = {
  fft: {
    slug: "fft",
    title: "FFT",
    english: "Fast Fourier Transform",
    category: "信号处理 / 频域分析",
    layer: "模型层",
    difficulty: 2,
    summary: "把时域异响信号拆到频率轴，对齐部件转速和谐波结构，是声学故障项目所有频域特征的基线算法",
    engineeringProblem: "从控制件声音中提取主频、谐波和异常频带，构造频域特征交给 RF 或 CNN 做故障分类",
    inputs: ["等间隔采样声音/振动序列", "采样频率 f_s", "同步转速/负载/工况"],
    outputs: ["频率-幅值谱或 PSD", "主频及谐波幅值", "频带能量、谐波比等特征"],
    principle: [
      "DFT 离散化计算有限长度序列频率组成；FFT 是高效计算 DFT 的算法族",
      "频率分辨率 Δf = 1/T，窗口长度 T 决定频谱精度",
      "加窗抑制频谱泄漏，hanning 窗口是工程默认选择",
    ],
    engineeringCase: "声学项目基线：先确认主频是否随转速同步变化、谐波是否异常，再决定是否上 STFT 或 CNN。稳定工况 FFT 足够，非平稳工况接 STFT。",
    suitable: ["稳态工况周期性异响", "频域特征提取喂给 ML 模型", "部件特征谐波识别"],
    unsuitable: ["强非平稳信号全域 FFT", "采样率不足或转速未同步", "单凭一个谱峰下结论"],
    pitfalls: ["采样率与频率分辨率混淆", "忽略加窗导致的谱泄漏", "不同转速样本直接对比固定频率", "环境噪声峰误判为故障特征"],
    next: [
      { label: "声学故障专题", href: "/business/acoustic" },
      { label: "STFT / 声谱图", href: "/business/acoustic" },
      { label: "Random Forest", href: "/models/random-forest" },
    ],
    projects: [
      { label: "声学故障：频域分析", href: "/business/acoustic" },
      { label: "AI 标定：NVH 评价扩展", href: "/business/calibration" },
    ],
  },
  "random-forest": {
    slug: "random-forest",
    title: "Random Forest",
    english: "Random Forest",
    category: "机器学习 / 集成学习",
    layer: "模型层",
    difficulty: 2,
    summary: "多棵决策树集成投票，给出特征重要性，对中小规模结构化数据极稳。诊断和声学项目的默认分类基线",
    engineeringProblem: "根据温度、电流、转速统计量、频带能量等结构化特征预测故障类型和严重等级",
    inputs: ["特征矩阵 X（每行一个样本）", "标签 y（故障类型/严重等级）", "按车辆/批次划分的训练/验证/测试集"],
    outputs: ["类别预测及概率", "Gini/置换特征重要性", "接 SHAP 输出单样本解释"],
    principle: [
      "Bootstrap 抽样使每棵树见不同样本子集，特征随机采样降低树间相关性",
      "分类投多数票，回归取均值；特征重要性来自随机置换后性能下降程度",
    ],
    engineeringCase: "诊断项目做故障分类，声学项目接在 FFT/MFCC 后做频谱特征分类。两者都是复杂深度网络的强基线——先跑 RF 看效果，再决定要不要上 XGBoost 或 CNN。",
    suitable: ["中小规模结构化数据", "需要特征重要性排序", "非线性特征-目标关系", "建立分类基线"],
    unsuitable: ["直接吃原始长波形", "精确外推连续物理量", "类别极度不平衡未评估"],
    pitfalls: ["只盯 Accuracy 不看召回率", "同车辆相邻片段泄漏到训练/测试集", "特征重要性误当因果", "类别不平衡不做专门处理"],
    next: [
      { label: "XGBoost", href: "/models/machine-learning" },
      { label: "SHAP 解释", href: "/models/machine-learning" },
      { label: "车辆诊断专题", href: "/business/diagnosis" },
    ],
    projects: [
      { label: "车辆诊断：故障分类", href: "/business/diagnosis" },
      { label: "声学故障：频谱特征分类", href: "/business/acoustic" },
    ],
  },
  "bayesian-optimization": {
    slug: "bayesian-optimization",
    title: "Bayesian Optimization",
    english: "Bayesian Optimization",
    category: "优化算法 / 黑盒优化",
    layer: "模型层",
    difficulty: 3,
    summary: "实车/台架试验昂贵时用代理模型在少量试验预算内找到最优标定参数，是 AI 标定参数寻优的首选方法",
    engineeringProblem: "在标定参数上下界和安全约束内，用最少实车试验找到驾驶性最优的参数组合",
    inputs: ["待优化参数及上下界", "每组参数的评价分数", "约束/噪声/多目标（可选）"],
    outputs: ["下一组建议试验参数", "当前最优参数集", "代理模型预测与不确定性", "Pareto 候选（多目标）"],
    principle: [
      "代理模型（高斯过程/TPE）拟合已有试验，同时估计不确定性",
      "采集函数（EI/UCB）在利用当前最优和探索未知之间权衡",
      "每完成一次试验更新代理模型，循环迭代",
    ],
    engineeringCase: "内部标定方案三模型链路：驾驶性评价模型 → BO 参数寻优 → 参数校验模型。BO 是寻优核心，必须配合安全校验和实车闭环。",
    suitable: ["单次试验昂贵", "参数维度中低、边界明确", "评价函数不可导", "希望显式利用历史试验"],
    unsuitable: ["维度极高且评价便宜", "评价函数不稳定", "安全约束无法表达"],
    pitfalls: ["代理模型预测当实车效果", "无独立安全校验直接下发", "多目标压成单分数权重未验证", "不同工况试验混在一起没归一化"],
    next: [
      { label: "AI 标定专题", href: "/business/calibration" },
      { label: "多目标优化", href: "/models/machine-learning" },
      { label: "Agent 工作流", href: "/applications/agent" },
    ],
    projects: [
      { label: "AI 标定：参数寻优", href: "/business/calibration" },
    ],
  },
};

export const applicationKnowledge: Record<string, KnowledgeDetail> = {
  agent: {
    slug: "agent",
    title: "Agent",
    english: "AI Agent",
    category: "大模型应用 / 工作流编排",
    layer: "应用层",
    difficulty: 3,
    summary: "Agent 不负责精确计算，负责把 LLM、模型、工具、状态、审批串成可追踪的多步工程流程",
    engineeringProblem: "把已有模型、数据脚本、知识库、参数校验和人工审批组织成可追踪的多步工程工作流",
    inputs: ["用户任务/工程事件", "当前状态 State", "可调用工具 Tools", "业务知识和安全规则"],
    outputs: ["结构化中间状态", "工具调用结果", "路由/继续/回退决策", "最终报告或下一步工程动作"],
    principle: [
      "LLM 负责理解任务和选工具，精确计算交给专用模型和工具",
      "State 跨步骤共享信息，避免每步从零开始",
      "Workflow 定义节点、路由、循环、终止和人工审批边界",
    ],
    engineeringCase: "内部驾驶性标定 Demo 用 LangChain + LangGraph 编排 4 个子 Agent，状态写入 CalibrationState。实车测试尚未接入，是工作流原型。",
    suitable: ["多步骤多工具工程任务", "需保存中间状态按结果路由", "需接入 RAG/模型/数据库/API", "需人工审批和过程日志"],
    unsuitable: ["单函数能完成的简单任务", "LLM 当精确计算器或底层控制器", "无安全边界让 Agent 自主下发高风险参数"],
    pitfalls: ["LLM 直接猜参数不调优化器", "无状态模型靠长 Prompt 隐式保存", "Agent 数量当能力指标", "缺 Human-in-the-loop 和回退"],
    next: [
      { label: "RAG", href: "/applications/rag" },
      { label: "LangGraph", href: "/models/deep-learning" },
      { label: "AI 标定专题", href: "/business/calibration" },
    ],
    projects: [
      { label: "AI 标定 Agent", href: "/business/calibration" },
      { label: "诊断 Agent", href: "/business/diagnosis" },
    ],
  },
  rag: {
    slug: "rag",
    title: "RAG",
    english: "Retrieval-Augmented Generation",
    category: "大模型应用 / 企业知识",
    layer: "应用层",
    difficulty: 3,
    summary: "企业故障案例和技术规范不在通用大模型里。RAG 先检索相关材料，再让 LLM 基于这些材料生成可追溯的回答",
    engineeringProblem: "从大量故障案例、技术文档和维修手册中快速检索相关证据，生成带来源的排查建议",
    inputs: ["PDF/Word/Markdown 文档", "文档切分后的 Chunk", "用户问题", "Embedding 与向量索引"],
    outputs: ["相关文档片段及来源", "带引用列表的 LLM 回答", "可继续交给 Agent 的结构化知识"],
    principle: [
      "文档解析与切分建立检索级 Chunk",
      "Chunk 编码为向量建立索引",
      "提问时检索相关 Chunk 再交给 LLM 生成并保留来源",
    ],
    engineeringCase: "RAG 适合故障后知识复用、标定经验检索和技术规范问答。不替代 CAN/声音的数值模型，而是补充文档知识的检索和引用。",
    suitable: ["企业内部知识问答", "历史案例检索", "技术规范辅助", "答案需可追溯来源"],
    unsuitable: ["精确时序预测", "控制策略实时计算", "文档质量差却期待高可靠答案"],
    pitfalls: ["切分过粗/过细丢失上下文", "只做向量检索不用元数据过滤", "检索不到仍让模型强行回答", "无来源展示无法工程复核"],
    next: [
      { label: "Agent", href: "/applications/agent" },
      { label: "文档数据", href: "/data" },
      { label: "车辆诊断专题", href: "/business/diagnosis" },
    ],
    projects: [
      { label: "诊断：相似案例检索", href: "/business/diagnosis" },
      { label: "标定：历史标定经验检索", href: "/business/calibration" },
    ],
  },
};